version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DB_HOST=db
      - DB_PORT=5432
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
  celery:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - app
      - rabbitmq
      - db
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672