"""initial migration

Revision ID: 32b5b24d5aac
Revises:
Create Date: 2024-12-07 18:30:58.741694

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "32b5b24d5aac"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
